{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "social-vibecoding-platform.fullname" . }}-migrator
  labels:
    {{- include "social-vibecoding-platform.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
automountServiceAccountToken: false
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "social-vibecoding-platform.fullname" . }}-postgresql
  labels:
    {{- include "social-vibecoding-platform.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
automountServiceAccountToken: false
{{- end }}
